language: python
cache:
  pip: true
  directories:
    - .eggs
python:
  - "2.7"
  - "3.5"
install:
  - pip install flake8
  - pip install coveralls
before_script:
  - "flake8 ."
script: coverage run setup.py test
after_success:
  coveralls
