language: python
cache:
  pip: true
  directories:
    - .eggs
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.11
install:
  - pip install Django==$DJANGO_VERSION
  - pip install beautifulsoup4
  - pip install requests
  - pip install prospector
  - pip install coveralls
before_script:
  - make lint
script: make test-with-coverage
after_success:
  - coveralls
